/* Daily thoughts — add more lines to this list, one quote per line.
   The app shows a different one each day and only repeats after the whole list has been shown. */
const QUOTES = [
  "Life is not about what you do. It is all about how you do it.",
  "As long as you think someone else is responsible for the way you are, you cannot become the way you want to be.",
  "Happiness is not something that needs to be extracted from the outside world.",
  "“Love is not a transaction.” It is an exuberance and sweetness of emotion.",
  "The human mind's beauty is its ability to imagine; its danger is getting lost in its imagination.",
  "Perception is the core of Yoga. Deeper perception leads to deeper experience and richer knowing.",
  "Spirituality is not about adopting another belief system; it is about experiencing life more profoundly.",
  "Yoga is not merely exercise; it is a technology for transforming the way you experience yourself and existence.",
  "Don't automatically do what everyone else is doing; discover what genuinely matters to you.",
  "Do not just learn from your failures; learn not to fail. Whatever you aspire for, figure out how to make it happen. Life is your Karma – it is your Making.",
  "Difficult situations can either strengthen you or break you; your response plays a significant role.",
  "You are given the raw material of life; what you create from it is your responsibility.",
  "Taking responsibility for your inner experience is the beginning of freedom.",
  "If your joy depends entirely on circumstances, your happiness will always be fragile.",
  "A relationship becomes healthier when you share your joy instead of trying to extract joy from someone else.",
  "Your thoughts are useful tools, but they become a problem when you mistake them for reality.",
  "What you perceive determines much of what you experience.",
  "You don't have to believe something simply because someone else says it is true.",
  "Meditation is about creating a space beyond the compulsiveness of your thoughts.",
  "The most beautiful moments in life are moments when you are expressing your joy, not when you are seeking it.",
  "Success should not come at the cost of losing yourself.",
  "Don't allow painful experiences to become permanent identities.",
  "Life becomes beautiful when you stop trying to control everything and learn to experience it fully.",
  "You may not control everything that happens, but you can transform the way you experience what happens.",
  "Don't make another person responsible for your happiness.",
  "Don't use love as a bargain: “I will love you if you behave the way I want.”",
  "Not every thought deserves your attention.",
  "If your perception expands, the world you experience also expands.",
  "The spiritual process begins when you become interested in knowing life beyond your existing limitations.",
  "If you want to be successful, don’t seek success – seek competence, empowerment; do nothing short of the best that you can do.",
  "Yoga begins to become meaningful when it changes your experience rather than merely your appearance.",
  "Ambition becomes powerful when it is accompanied by clarity rather than desperation.",
  "A difficult situation doesn't have to determine the quality of your entire life.",
  "The quality of your life is determined more by your inner experience than by your external circumstances.",
  "Don't wait for someone else to change before you begin changing yourself.",
  "When your joy comes from within, you can share it rather than demand it.",
  "The deeper your sense of love, the less you need to possess another person.",
  "A thought can be created by you without having to become your reality.",
  "Learning to see clearly is more important than simply collecting more beliefs.",
  "You are not the body. You are not even the mind. You are the consciousness which is aware of both.",
  "Don't confuse information about spirituality with actual spiritual experience.",
  "Attention to the smallest aspects of life can itself become a form of yogic awareness.",
  "Your actions become more effective when your inner state is stable.",
  "Suffering often grows when you constantly argue with reality instead of responding intelligently to it.",
  "Don't postpone living until everything around you becomes perfect.",
  "Your life becomes powerful when you stop looking for someone to blame.",
  "Life becomes joyful when you stop treating every situation as a transaction.",
  "Love becomes expansive when it isn't limited by expectation.",
  "The mind can either become a powerful instrument or an unnecessary source of suffering.",
  "Meditation is not about being in a special place or situation. It is about turning inward.",
  "Don't rush to conclusions when you can first learn to observe.",
  "Spirituality is ultimately about becoming less limited in your experience of life.",
  "Your body, breath, mind and emotions can become instruments rather than obstacles.",
  "Don't measure your life entirely through other people's definitions of success.",
  "Freedom means having enough inner space that circumstances don't completely dictate your experience.",
  "Existence does not need to fit neatly into your ideas for you to experience its beauty.",
  "Whatever happens around you, your response is still something you can work upon.",
  "Joy is not a reward for success; it can become the foundation from which you live.",
  "Relationships suffer when two people are constantly trying to get something from each other.",
  "Every moment, every situation, every breath is a possibility. To make of it what you will is entirely up to you.",
  "If you learn to observe your thoughts, you create space between yourself and your mental activity.",
  "Awareness means seeing something as it is, rather than only as you want it to be.",
  "Instead of constantly asking what you should believe, explore what you can experience.",
  "When you become deeply attentive, ordinary activities can become profound experiences.",
  "What matters is not simply how much you accomplish, but the quality with which you live while accomplishing it.",
  "You become stronger when you learn from an experience instead of merely resisting it.",
  "The more deeply you perceive life, the more profound your experience becomes.",
  "Greater responsibility doesn't have to mean greater burden; it can mean greater freedom.",
  "The more inclusive your experience of life becomes, the less room there is for unnecessary suffering.",
  "The quality of your life depends on how well you manage your body, mind, emotions, and the world around you.",
  "Instead of asking whether someone completes you, learn to experience yourself as complete.",
  "Your imagination can create wonderful possibilities, but it can also manufacture unnecessary fears.",
  "The more attentive you become, the more dimensions of life become available to you.",
  "The inward journey isn't about travelling somewhere physically.",
  "The purpose of inner work is not to escape life but to experience it more fully.",
  "If you constantly compare yourself with others, even success can become a source of suffering.",
  "Fear becomes less powerful when you stop constantly feeding it with your imagination.",
  "Life is happening in every moment; don't miss it while thinking about the past or future.",
  "If you take charge of yourself, circumstances have less power over you.",
  "Whatever you do, do it with total involvement – that is all that matters.",
  "You don't need a perfect life to experience profound joy.",
  "Love should not become another name for control.",
  "Don't allow yesterday's experiences to completely dictate today's perception.",
  "A limited perception can make a limitless existence appear very small.",
  "Turning inward is not a journey. There is no distance.",
  "Greater awareness can make even simple moments extraordinarily rich.",
  "Let your goals come from your own understanding rather than social pressure.",
  "Compassion can be deeply liberating because it moves you beyond narrow self-interest.",
  "Your experience of life can become larger than the limitations of your identity.",
  "To live in full intensity, you need an inner stillness. Without that, everything wears you out.",
  "Growth begins when you stop demanding that the world adjust itself to you.",
  "Instead of asking, “What can life give me?”, ask what you can contribute to life.",
  "When you are joyful by yourself, relationships can become a sharing rather than a dependency.",
  "A mind that is constantly judging cannot perceive life clearly.",
  "Yoga is fundamentally about enhancing your experience and perception of life.",
  "Your identity can be useful without becoming a prison.",
  "Don't turn meditation into another achievement; allow it to become a way of being.",
  "You can pursue great things without making yourself miserable in the process.",
  "When you recognize how little you truly understand about existence—from the atomic to the cosmic—you naturally become more humble.",
  "Sadhana is not a ritual. It is your longing to include everything in your experience.",
  "When you stop making life about yourself, existence becomes much bigger.",
  "You don't have to become somebody else; you have to become the fullest possibility within yourself.",
  "Inner wellbeing is not something you should negotiate with the outside world.",
  "The quality of a relationship depends greatly on the quality of the people bringing themselves into it.",
  "The ability to pay attention is more valuable than endlessly accumulating information.",
  "Instead of constantly seeking answers, learn to look more deeply.",
  "The deeper spiritual possibility is to experience yourself as life, rather than only as a personality.",
  "Inner transformation is less about adding something and more about removing limitations.",
  "Whatever you do, bring your whole attention to it.",
  "A spiritual process means you are moving towards a dimension where experiential knowledge becomes the only truth.",
  "Do not look for anything. Do not look for the meaning of life. Do not look for God. LOOK – That Is All.",
];
